"""Data models for the chat pipeline."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class MessageRole(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class QueryStatus(str, Enum):
    SUCCESS = "success"
    ERROR = "error"
    BLOCKED = "blocked"  # query was rejected for safety


@dataclass
class ChatMessage:
    """A single message in the conversation."""

    role: MessageRole
    content: str
    timestamp: str = ""


@dataclass
class GeneratedQuery:
    """A SQL query generated by the SQL Generator agent."""

    sql: str
    reasoning: str = ""
    target_connection_id: str = ""  # which connection to execute against


@dataclass
class QueryResult:
    """Result of executing a SQL query."""

    status: QueryStatus
    columns: List[str] = field(default_factory=list)
    rows: List[List[Any]] = field(default_factory=list)
    row_count: int = 0
    truncated: bool = False
    error_message: str = ""
    execution_time_ms: float = 0.0


@dataclass
class ChatTurn:
    """A complete turn: user question → generated SQL → results → answer."""

    user_question: str
    generated_sql: str = ""
    sql_reasoning: str = ""
    query_result: Optional[QueryResult] = None
    answer: str = ""
    error: str = ""
    timestamp: str = ""


# Maximum rows returned